<a href="https://colab.research.google.com/github/leeds1219/Deep_learning_project/blob/main/DiveintoDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Preliminaries

In [14]:
#2.1.1 Getting Started

import torch

# A tensor is an array of numerical values.

x = torch.arange(12, dtype=torch.float32)
x

# arange(n) create a vector of evenly spaced values starting at 0
# and ending at n(not included)
# each values of x is called element of tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
# number of elements
x.numel()

12

In [16]:
# shape of tensor(the length along each axis)
x.shape

torch.Size([12])

In [17]:
# changing the shape of a tensor
X = x.reshape(3, 4)
X

# note that reshape is redundant x.reshape(3,4) is equivalent to x.reshape(-1,4)
# or x.reshape(3,-1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
# zero tensor
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
# one tensor
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
# random (tensor with elements drawn from Gaussian distribution)
torch.randn(3,4)

tensor([[-0.2245, -1.0946,  0.3518,  1.1990],
        [-0.0396,  0.5453, -1.1508, -0.1254],
        [ 0.0345, -0.4640, -0.7160,  1.5059]])

In [21]:
# directly setting the elements
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [22]:
# 2.1.2. Indexing and Slicing

# X[start:stop] X[-1] means last row, X[1:3] means second and third row
# remember that index starts from 0 in Python

X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [23]:
# writing elements of a matrix by specifying indices

X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
# assigning multiple elements of the same value

X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [25]:
# 2.1.3. Operations

# elementwise operations are useful
# exp(x) operates e^(x) elementwise

torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [ ]:
# addition + subtraction - multiplication *
# division / exponentiation ** operators

x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

In [26]:
# linear algebraic operations
# dot products & matrix multiplications <- in section 2.3

# concatenate multiple tensors stacking tem end to end and
# example that concatenate two matrices along rows instead of columns

X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [28]:
# binary tensor via logical statements

# For each position i, j, if X[i, j] and Y[i, j] are equal, then the
# corresponding entry in the result takes value 1, otherwise it takes value 0.

X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
# sum

X.sum()

tensor(66.)

In [30]:
# 2.1.4 Broadcasting # very important concept!!

# for two tensors that differ in shape

# Broadcasting works according to the following two-step procedure:
# (i) expand one or both arrays by copying elements along axes with length 1
# so that after this transformation, the two tensors have the same shape;
# (ii) perform an elementwise operation on the resulting arrays.

a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))